### ISSUE TITLE
Update theme to support hugo v0.29

### ISSUE THREAD

**Issue by erictheise** [terranodo/tegola-docs#6]
There seems to be more to it than running `hugo server`. I'd be happy to submit some typo and other corrections to your docs but anything much beyond `brew install hugo` is out of scope for me.

```
$ hugo server
Started building sites ...
ERROR 2017/10/05 16:44:10 Error while rendering "page": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "head" .>: error calling partial: template: theme/partials/head.html:73:12: executing "theme/partials/head.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput
ERROR 2017/10/05 16:44:10 Error while rendering "section": template: theme/_default/list.html:1:3: executing "theme/_default/list.html" at <partial "head" .>: error calling partial: template: theme/partials/head.html:73:12: executing "theme/partials/head.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput
ERROR 2017/10/05 16:44:10 Error while rendering "home": template: theme/index.html:1:3: executing "theme/index.html" at <partial "head" .>: error calling partial: template: theme/partials/head.html:73:12: executing "theme/partials/head.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput

Built site for language en:
0 draft content
0 future content
0 expired content
5 regular pages created
14 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 7 ms
Watching for changes in /Users/erictheise/Repos/erictheise/tegola-docs/{content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by ARolek** [comment]
@erictheise thanks for the report. What version of hugo are you running?

**Comment by erictheise** [comment]
Just installed via homebrew, I'm running:

`Hugo Static Site Generator v0.29 darwin/amd64 BuildDate: 2017-10-05T16:44:00-07:00`

**Comment by ARolek** [comment]
@erictheise ok thanks. that's the newest version. I will test and circle back.

**Comment by ARolek** [comment]
@erictheise looks like these docs were built using hugo 0.15. I just tested them with 0.15 and they work fine. Using 0.29 is causing issues. The docs will need to be updated. So a few options: 
- Download [hugo 0.15](https://github.com/gohugoio/hugo/releases/tag/v0.15)
- Wait for us to update them. I'm planning on doing this once we finalize v0.4.0 of tegola
- Help with the migration to hugo 0.29. ;-)

**Comment by erictheise** [comment]
@ARolek, while I muse over my options am I correct in thinking that the master documents are the markdown files in `/content/`?

**Comment by ARolek** [comment]
@erictheise apologies on the delay. Yes the markdown files in the `/content/` directory host everything that will be rendered by hugo. Looks like you found that already according to your pull request. I will review it shortly. Thanks for helping us improve the documentation!

**Comment by ARolek** [comment]
@erictheise doc theme has now been updated. Thanks for the report!

**Comment by erictheise** [comment]
Fantastic! Thanks @ARolek, I can confirm that the docs site loads locally just fine now.
