### ISSUE TITLE
'Getting started' suggests excessive privileges for tegola user

### ISSUE THREAD

**Issue by johnwbryant** [terranodo/tegola-docs#8]
In his blog post "[Hello Tegola](http://erictheise.com/blog/2017/11/13/hello-tegola)", @erictheise points out (rightly) that the Getting Started docs offer "_the inexcusable advice to give the tegola role PostgreSQL superuser privileges_". I have to take the blame for this, I put that in during a code sprint when there wasn't enough time to troubleshoot connection problems, and that was the sleazy fix. Never got back to it until now (shaaaaame).

Will put in a PR shortly that fixes this :)

**Comment by erictheise** [comment]
You're a good man, @johnwbryant; thanks for taking my strident language in the spirit it was meant – bettering things in the long run – and circling back to address this.

**Comment by gdey** [comment]
@erictheise thanks for the blog post and write up. Like some of the suggestions for keeping passwords out of the config files, and shell scripts. I ended up putting in the `dbcredentials.sh` for that very reason but never documented it.  Really should document it.
